### ISSUE TITLE
Increase browser support with something like babel-polyfill

### ISSUE THREAD

**Issue by schne324** [schne324/dragon-drop#13]

**Comment by scottaohara** [comment]
Hi @schne324 

Was giving this a test with JAWS + IE11 today.  Maybe this issue is why it wasn't working as expected for me there, but was working fine in firefox?

**Comment by schne324** [comment]
Hey @scottaohara, thanks for checking it out! What wasn't working as expected in IE?

I think I remember something funky with IE/JAWS last time I tested this, I want to say I had to force it into focus mode for it to work as intended but I could be wrong.

I'll check this out next time I have a chance 😄

**Comment by scottaohara** [comment]
Hey again.

So in JAWS+Firefox ESR I had to specifically turn off JAWS's virtual cursor (<kbd>JAWS key</kbd> + <kbd>Z</kbd>) to allow me to move the items, and once I did that it worked just fine.

In IE11 though, this didn't have any effect and I couldn't move the items regardless of if the virtual cursor was on or off.  Pressing <kbd>JAWS key</kdb> + <kbd>Space</kbd> in either Firefox or IE also didn't allow the movement of the items. The virtual cursor persisted.

I have not tested Chrome, nor have I tested NVDA beyond being paired with firefox.  Going into Focus Mode with NVDA + Firefox worked as expected.

Let me know if you have any questions beyond this, I'd be more than happy to provide any missing context you need.

**Comment by scottaohara** [comment]
@schne324 FYI, I went and just threw all the JS into [babeljs.io](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=Q&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=) and then retested with IE11 and reording is working with the keys I mentioned in my last message.

**Comment by schne324** [comment]
Thats weird because the source is already getting passed through babel-preset-2015 (last night I actually updated to env but that hasn't been released)

**Comment by scottaohara** [comment]
is it?  hmm..  prior to my previous message today, I downloaded the source from master and took a look in dragon-drop.js in the dist folder and it's full of fancy fat arrow functions that make IE all sad and confused :)

**Comment by schne324** [comment]
Ah ok, thanks for looking into this :)

**Comment by schne324** [comment]
As realized after #23 was raised, I was (uselessly) using a dependency (to merge objects) which was using things like `const`. Since I'm already using babel to transpile the code, I was able to utilize object spread instead which means the dist bundle no longer has any signs of es6 stuff.  Please check version 3.2.4 for the latest update.

Closing this now but if you happen to check 3.2.4 update in IE11 and its still having issues let me know and I will reopen this.

Thanks!
