### ISSUE TITLE
MirrorContainer property missing.

### ISSUE THREAD

**Issue by LouVerdun** [schne324/dragon-drop#17]
Hello, 

I have this issue where the mirrored (moving) div is appended in the body. In dragula, we have the option of passing a scope with the attribute `mirrorContainer: yourcontainer`.

`
dragula([this.reorderableList], {
       mirrorContainer: this.reorderableList
});
`

Is it possible to have this option accessible from the Drag on Drop interface ? I can't manage to make it work without it...

Thank you !

**Comment by schne324** [comment]
So just to clarify - would opening up a DragonDrop option `dragulaOptions` which let's you pass arbitrary options through to dragula solve this problem?

something like this
```js
new DragonDrop(container, {
  dragulaOptions: {
    mirrorContainer: this.reorderableList,
    copy: false,
    removeOnSpill: false
  }
});
```

**Comment by LouVerdun** [comment]
That should work indeed! I'll try that and get back to you. Thank you for your answer!

**Comment by schne324** [comment]
@LouVerdun Don't try it yet! I still need to implement this, I just wanted to confirm that adding this option would solve your problem

**Comment by schne324** [comment]
@LouVerdun `drag-on-drop@3.3.0` [supports passing dragula options through](https://github.com/schne324/dragon-drop#dragulaoptions-object)

Sorry for the long delay but I hope this helps!
