### ISSUE TITLE
Dragula - Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by mrweiner** [schne324/dragon-drop#19]
The docs say to use `dragonDrop.dragula.on('drop', ...);` for mouse events, but no matter what I do I can't seem to actually access dragula. Using the 'nested lists' example from [the demo](http://schne324.github.io/dragon-drop/demo/),  I've tried:

- `DragonDrop.dragula.on('drop', ...)`
- `dragons.dragula.on('drop', ...)`
- `dragon.dragula.on('drop', ...)` (within `dragons.forEach`)

Each of those seems to throw `Uncaught TypeError: Cannot read property 'on' of undefined`. Any thoughts?

**Comment by schne324** [comment]
Ah sorry, just realized that in the special case of nested lists, I forgot to add dragula to each instance. Thanks for finding this bug, I will push a patch for this right now

**Comment by schne324** [comment]
just merged in a patch for this - will be tagging 3.2.3 momentarily

**Comment by schne324** [comment]
ok dragon drop version 3.2.3 has the fix.

thanks!

**Comment by schne324** [comment]
so the way this works is that each instance has it's own `dragula` meaning you can now:

```
const dragons = new DragonDrop(lists, {
  nested: true,
  handle: false,
  item: ':scope > li'items
});

dragons.forEach(dragon => {
  dragon.dragula.on('drop', ...);
});
```

By the way, as I'm typing this I just realized that this is another gap in the special case of nested lists -- you _should_ be able to `dragon.on('drop', ...)` (thats how unnested dragons work). I guess I will be fixing that as well 😄

**Comment by mrweiner** [comment]
You rock, thanks! Beats my mutation observer hack by a lightyear or so. For the record `dragon.on('drop', ...)` already works for keyboard actions on nested lists.
