### ISSUE TITLE
Using keyboard to reorder dynamically added list entries

### ISSUE THREAD

**Issue by timsn** [schne324/dragon-drop#26]
I have an issue with adding new list entries after DragonDrop was applied to a list.
In my case I have a list containing a few items and apply DragonDrop to this list. Everything works here as expected. 

At some point I want to add a new list entry to this list dynamically. After adding this entry (by using the jQuery.append() function) the reordering using the mouse works fine but selecting the new entry is not possible and thus the reordering using the keyboard also does not work.

I would consider this as an issue or is there any way to "refresh" DragonDrop or completely "destroy" DragonDrop on this list and reapply it once the new list item is added?

I've prepared a little example [here](https://jsfiddle.net/nay052vq/15/). There is a button below the list which adds a new list entry dynamically. After the new entry is added you can't reorder it by using the keyboard.

**Comment by schne324** [comment]
there is a public method `initElements` which should do the trick for you. All you have to do is pass the container element reference to `dragonDrop.initElements`.

I actually have a working example of [react dragon drop with dynamic items](https://codepen.io/schne324/pen/dZOGeG)

**Comment by schne324** [comment]
UPDATE -- this _used to_ work...I will look into what is causing this bug and let you know when theres a fix

**Comment by schne324** [comment]
@timsn I tracked down the problem and just published a patch release `drag-on-drop@3.3.2`

Thanks for finding the bug!
