### ISSUE TITLE
Feature Request: support for dragging between multiple containers

### ISSUE THREAD

**Issue by jh4rri** [schne324/dragon-drop#28]
I have created a drag and drop project whose basis is to allow items from container 1 to be draggable to container 2 and vice versa, as well as allowing items to be reordered within their containers.  For the first iteration of my project I have achieved this using dragula.

However, I need to make this accessible and was looking at using dragon-drop, however I don't think it is currently possible to implement dragon-drop in this way, is that correct?

**Comment by schne324** [comment]
Correct, this is not currently possible but is definitely on the roadmap -> see #11
