### ISSUE TITLE
Bug: Clicking on handle creates focused state

### ISSUE THREAD

**Issue by lcecil** [schne324/dragon-drop#30]
**Description**
When I click on the drag handle, it puts that element in a state of `aria-pressed="true" data-drag-on="true"`. I only want those things to happen when the element is _truly_ being dragged.

**Steps to Repro:**

1. In the "Rank the bands" example on the demo page, click on the "Leftover salmon" handle (handle/item is in the state described above).
2. Click anywhere else on the page or tab to put focus on the first handle.

**Expected Result**
State described above is only applied in a true "grab" (when I click+drag or when I hit the space/enter key).

**Actual Result**
State is applied on click of the item and cannot be removed, unless the user selects a different item from the list with the mouse or keyboard.

**Additional Info**
I had an idea for fixing this:
1. Create a custom event in the `onKeyDown` method - `const event = new Event('grab');`
2. Then dispatch that event where it's calling `target.click()` --> `target.dispatchEvent(event)`
3. In `initClick()` set each handle to listen for the new event `handle.addEventListener('grab', ...)`
4. Add a `document.addEventListener('click', ...)` to remove any of the "grabbed" state attributes, if the user clicks anywhere else in the document.

#4 is maybe not the best solution, but an idea. Let me know what you think of the above.

**Comment by schne324** [comment]
I think the most we should do here is number 4 (unpress/remove grabbed state with clicks outside of the list) because I think using a combination of mouse + keyboard (or other AT control) should remain supported.  That way, a user clicking (with a mouse) on the handle and then using a keyboard to actually perform the reordering is still supported.

Thoughts?

**Comment by lcecil** [comment]
I can understand that thought. My situation is such that I want my entire item to be draggable (no handle) AND I have some controls within the item. So when a user clicks on the select box, it activates the drag state of the item, even if that wasn't what they were intending to do (see image below):

![image](https://user-images.githubusercontent.com/15719045/45569034-3782ab80-b813-11e8-896e-4671b760dcce.png)

I realized that this is a pretty specialized case, so it's entirely up to you on how to proceed!

Implementing number 4 would be wonderful though, thanks much!

**Comment by schne324** [comment]
to prevent the item from being pressed, you could add a click listener on the select and call `event.stopPropagation()` so dragon drop never even hears the event 😄

**Comment by lcecil** [comment]
Ah ok, thanks for the tip!
