### ISSUE TITLE
Question: Unit Testing with DragonDrop

### ISSUE THREAD

**Issue by lcecil** [schne324/dragon-drop#33]
Hello again,

I was wondering if you have any recommendations for unit testing the dragon-drop functionality in an Angular app. I've set up my code according to the documentation:

```
import DragonDrop from 'drag-on-drop';

// Other component stuff goes here

this.keyboardDragon = new DragonDrop(this.dragon.nativeElement, {
   item: 'mapping-item-source-dest-position',
   handle: false,
   activeClass: 'gu-mirror-keyboard'
});

this.keyboardDragon.on('dropped', (_, item) => {
  // Do some stuff
});
```

But when I run my jasmine tests, I get the following error:
`TypeError: drag_on_drop_1.default is not a constructor`

Any ideas?

**Comment by schne324** [comment]
I've never used dragondrop on an angular app but the TypeError sounds like you have an issue with your transpiler not supporting "standard" modules
