### ISSUE TITLE
New items cannot be dragged

### ISSUE THREAD

**Issue by tdhooper** [schne324/dragon-drop#37]
After initialisation, new items added to the container can be moved with the mouse, but not the keyboard.

For an example, go to https://schne324.github.io/dragon-drop/demo/ and add a new item to the first demo by running this in the console:

    $('#demo-1').appendChild($('#demo-1').lastElementChild.cloneNode(true))

Tabbing onto the new handle and pressing return does nothing, however dragging it with the mouse works.

**Comment by tdhooper** [comment]
Aha, I just found `initElements` from reading the code, and then I found #26. Maybe a note about this in the docs could help?

**Comment by schne324** [comment]
@tdhooper good call, this should definitely be documented. I have created #38 to address this. I can't promise to get around to it ASAP but it will get done eventually (plus this is open source so maybe someone else will pick it up!)

Thanks!
